title: SLAM Arxiv Daily
description: Automatically updated SLAM / VSLAM / Foundation-SLAM arXiv papers, refreshed daily via GitHub Actions
show_downloads: true
#theme: jekyll-theme-slate

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme

github:
  zip_url: https://github.com/thanhnguyencanh/SLAM-Resources
  another_url: https://github.com/thanhnguyencanh/SLAM-Resources
